kind: test
apiVersion: api.ibm.com/v1
metadata:
  name: Create task
  namespace: task-management
  version: "1.0"
  tags: []
spec:
  api:
    $ref: task-management:task_management_api:1.0.0
  environment:
    $ref: task-management:sandbox-ngw:1.0
  request:
    - method: POST
      resource: /tasks
      headers:
        - key: content-type
          value: application/json
        - key: accept
          value: application/json
      auth:
        noauth: true
      payload:
        raw:
          json: |-
            {
                "creator": "Stéphane",
                "assignee": "Fabrice",
                "status": "todo",
                "description": "Arroser les plantes",
                "targetDate": "2026-01-23",
                "comment": "Et pas avec de l'eau de vie !"
            }
      endpoint: https://task-management-api-product-sandbox-user-demo-org.nanogw.apps.itz-q037mu.infra01-lb.fra02.techzone.ibm.com/1.0.2
      assertions:
        - $ref: task-management:Create Task Assertions:1.0
    - method: GET
      resource: /tasks
      headers: []
      auth:
        noauth: true
      assertions:
        - $ref: task-management:List Task Assertions:1.0
      endpoint: https://task-management-api-product-sandbox-user-demo-org.nanogw.apps.itz-q037mu.infra01-lb.fra02.techzone.ibm.com/1.0.1
      skipped: true
