kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: Policies-wM
  namespace: task-management
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: task-management:invoke-Policies-wM:1.0
