kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: task_management_api
  namespace: task-management
  version: 1.0.0
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./task_management_api-spec.yml
  policy-sequence:
    - $ref: task-management:Policies:1.0
    - $ref: task-management:Policies-wM:1.0