kind: Product
apiVersion: api.ibm.com/v1
metadata:
  name: Tasks Product
  namespace: task-management
  version: '1.0'
  tags: []
  description: ''
spec:
  apis:
    - $ref: task-management:task_management_api:1.0.0
  plans:
    - $ref: task-management:Default:1.0
  extensions:
    portal-config:
      apiVersion: api.ibm.com/v1
      spec:
        visibility:
          view:
            type: public
            orgs: []
            enabled: true
            tags: []
          subscribe:
            type: authenticated
            orgs: []
            enabled: true
            tags: []
