kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-Policies-wM
  namespace: task-management
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  endpoint:
    http:
      target:
        timeout: 30
        url: >-
          'http://task-management.tasks.svc.cluster.local:8000' &
          $relativeUrl('request')
        version: HTTP/1.1
        urlType: jsonata
  extensions:
    webm-gateway:
      apiVersion: api.ibm.com/v1
