kind: Telemetry
apiVersion: api.ibm.com/v1
metadata:
  name: tasks-telemetry
  namespace: tasks-ngw
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  verbosity:
    - level: detailed
      onSuccessTrimTo: detailed
      inboundLevel: detailed
      outboundLevel: detailed
      operations:
        - method: GET
        - method: POST
        - method: PUT
        - method: DELETE
