kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: tasks-invoke
  namespace: tasks-ngw
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        timeout: 30
        url: >-
          'http://task-management.tasks.svc.cluster.local:8000' &
          $relativeUrl('request')
        urlType: jsonata
        version: HTTP/1.1

